### ISSUE TITLE
Device disconnects after connection parameter updates

### ISSUE THREAD

**Issue by TorstenRobitzki** [TorstenRobitzki/bluetoe#13]
Details are following...

**Comment by xnlcasad** [comment]
Just hit this issue.

**Comment by TorstenRobitzki** [comment]
Do you have a sniff of the situation?

**Comment by xnlcasad** [comment]
I'll try to get one.

**Comment by TorstenRobitzki** [comment]
Not reproducible.

**Comment by TorstenRobitzki** [comment]
This seems to happen, when the transmitWindowOffset of the LL_CONNECTION_UPDATE_REQ is 0. Reproducible using nRF Connect for example.

**Comment by TorstenRobitzki** [comment]
Looks like the bug was introduced with 950a3230fc534b26a9c3beb2e24b87b2c94c63b4
